% Veni Sancte Spiritus (Pentecost Sequence) in Chinese and Latin.
%
% Typeset for Mary Help of Christians Chinese Catholic Parish, Edmonton, Canada
% by Anthony Fok, 2015-04-22 to 2015-04-23
%
% This work is licensed under a
% Creative Commons Attribution-ShareAlike 4.0 International License.

%
% Jianpu (numbered musical notation) in
% 懇求主聖神降臨_Veni_Sancte_Spiritus_頌恩626_jianpu.ily
% was generated by Silas C. Brown's excellent jianpu-ly.py script v1.143

% Removed reference to MHOC, and transposed from C to D on 2015-05-07
\version "2.18.2"

\header {
  title = \markup {
    懇求主聖神降臨
    \override #'(font-name . "Gentium Book Basic Bold") {
      %Veni Sancte Spiritus
      VENI SANCTE SPIRITUS
    }
  }
  subtitle = "五旬節(聖神降臨)繼抒詠 (Pentecost Sequence)"
  copyright = \markup {
    \override #'(baseline-skip . 2)
    \teeny {
      \left-column {
        \small \line {
          可將會眾分為兩邊詠唱此曲。後立刻接唱：福音前歡呼 - Alelluia!
        }
        \line {
          詞：Pope Innocent III (1198–1216)
          ※ 譯：採自【聖歌選集 - No. 38】1969 (香港)
          ※ 曲：傳統額我略曲 (第一調式)
        }
        \line {
          來源：新《頌恩》第626首 (天主教香港教區 2005)
          % ※ 雙語版植譜：加拿大愛民頓瑪利亞進教之佑華人天主堂 (2015-04-23)
          ※ 此雙語版以 LilyPond 植譜 — www.lilypond.org (af, 2015-04-23, 2017-03-27, Edmonton, AB)
        }
      }
    }
  }
  tagline = ##f
}

#(set-global-staff-size 19.5)

\paper {
  #(set-paper-size "letter")
  %ragged-last = ##t
  
  %top-margin = 0.75\in
  left-margin = 0.5\in
  right-margin = 1\in
  %bottom-margin = 5\mm
  % http://www.lilypond.org/doc/v2.18/Documentation/notation/flexible-vertical-spacing-paper-variables
  %markup-system-spacing #'basic-distance = #-20
  %markup-system-spacing #'padding = #1
  %system-system-spacing #'basic-distance = #14
  system-system-spacing #'padding = #1.2
  min-systems-per-page = 6
}


global = {
  %\key d \dorian
  \key e \dorian
  %\time 4/4
  \cadenzaOn
  % http://comments.gmane.org/gmane.comp.gnu.lilypond.general/86734
}

bb = { | \bar "'" }
bl = { | \bar "|" }
bll = { | \bar "||" \break }

sd = { \set melismaBusyProperties = #'() \slurDashed }
ss = { \slurSolid \unset melismaBusyProperties }


melody = \relative c' {
  \tempo "Recitativo legato"
  \global
  \autoBeamOff
  
  d8 e fis g fis[ e] d e4 \bl  g8 a b c b[ a g] a b4 \bl d,8 e g a g[ fis e] d e4 \bll
  %c8 d e f e[ d] c d4 \bl  f8 g a bes a[ g f] g a4 \bl c,8 d f g f[ e d] c d4 \bll
  
  b'8 d e e d[
  \once \override Voice.Accidental.stencil = ##f
  cis] d e4 \bl  d8 b d[ cis] a g[ fis] e d4 \bl  a'8 g a[ b] a g[ fis e] d e4 \bll
  %a'8 c d d c[ b] c d4 \bl  c8 a c[ b] g f[ e] d c4 \bl  g'8 f g[ a] g f[ e d] c d4 \bll
  
  e'8 e d[ cis] d e[ d] cis b4 \bl  g8 e d e g a g4 \bl  a8[ b] c b a g[ fis e] d e4 \bll
  %d'8 d c[ b] c d[ c] b a4 \bl  f8 d c d f g f4 \bl  g8[ a] bes a g f e[ d c] d4 \bll
  
  b'8 d
  \once \override Voice.Accidental.stencil = ##f
  cis[ b] cis d[ cis] b a4 \bl  b8 b g[ fis] g a[ g] fis e4 \bl  fis8 a b a d cis b4 \bll
  %a8 c b[ a] b c[ b] a g4 \bl  a8 a f[ e] f g[ f] e d4 \bl  e8 g a g c b a4 \bll
  
  e8 e a, b d cis b4 \bl  b8 c b[ a] b g a g4 \bl  fis8 a b e, g fis e4 \bll
  %d'8 d g, a c b a4 \bl  a8 bes a[ g] a f g f4 \bl  e8 g a d, f e d4 \bll
  
  e8[ fis e] d4( e) \bb  d8 g fis[ e] e4 | \bar "|."
}

fpa = \once \override LyricText #'self-alignment-X = #-0.72
fpb = \once \override LyricText #'self-alignment-X = #0.72

chineseText = \lyricmode {
  \override LyricText.font-size = #2.5

  \set stanza = #"1. "
  懇 求 主 聖 神 降 \fpa 臨， 賜 我 等 天 上 神 \fpa 光， 啟 導 諸 信 者 之 \fpa 心。
  祢 是 窮 人 的 慈 \fpa 父， 祢 是 恩 寵 的 施 \fpa 主， 祢 是 眾 心 的 暉 \fpa 曙。

  祢 是 苦 者 的 安 \fpa 慰， 祢 是 善 靈 的 良 \fpa 衛， 祢 普 施 珍 美 德 \fpa 惠。
  祢 予 勞 者 以 憩 \fpa 息， 祢 予 疲 者 以 毅 \fpa 力， 祢 予 泣 者 以 撫 \fpa 翼。

  祢 是 普 世 的 福 \fpa 星， 祢 以 神 妙 的 光 \fpa 明， 照 耀 信 眾 的 心 \fpa 靈。
  沒 有 祢 的 聖 寵 \fpa 祐， 人 類 必 無 所 造 \fpa 就， 更 不 免 於 諸 罪 \fpa 咎。

  請 清 除 一 切 穢 \fpa 污， 請 灌 澤 心 靈 涸 \fpa 沽， 請 療 我 們 的 殘 \fpa 腐。
  求 賜 冥 頑 者 默 \fpa 化， 求 賜 冷 淡 者 光 \fpa 明， 求 賜 迷 途 者 返 \fpa 家。

  諸 欽 崇 祢 的 靈 \fpa 魂， 特 虔 誠 向 祢 奔 \fpa 馳， 祈 充 以 聖 神 七 \fpa 恩。
  懇 頒 殊 福 於 德 \fpa 勳， 廣 施 救 贖 之 鴻 \fpa 恩， 並 賜 永 生 與 爾 \fpa 民。

  \set stanza = #"(齊唱)"
  A -- men.  Al -- le -- lú -- ia.
}

chineseTextOdd = \lyricmode {
  \override LyricText.font-size = #2.5

  \set stanza = #"1. "
  懇 求 主 聖 神 降 \fpa 臨， 賜 我 等 天 上 神 \fpa 光， 啟 導 諸 信 者 之 \fpa 心。
  \set stanza = #"3. "
  祢 是 苦 者 的 安 \fpa 慰， 祢 是 善 靈 的 良 \fpa 衛， 祢 普 施 珍 美 德 \fpa 惠。
  \set stanza = #"5. "
  祢 是 普 世 的 福 \fpa 星， 祢 以 神 妙 的 光 \fpa 明， 照 耀 信 眾 的 心 \fpa 靈。
  \set stanza = #"7. "
  請 清 除 一 切 穢 \fpa 污， 請 灌 澤 心 靈 涸 \fpa 沽， 請 療 我 們 的 殘 \fpa 腐。
  \set stanza = #"9. "
  諸 欽 崇 祢 的 靈 \fpa 魂， 特 虔 誠 向 祢 奔 \fpa 馳， 祈 充 以 聖 神 七 \fpa 恩。

  \set stanza = #"(齊唱)"
  A -- men.  Al -- le -- lú -- ia.
}

chineseTextEven = \lyricmode {
  \override LyricText.font-size = #2.5

  \set stanza = #"2. "
  祢 是 窮 人 的 慈 \fpa 父， 祢 是 恩 寵 的 施 \fpa 主， 祢 是 眾 心 的 暉 \fpa 曙。
  \set stanza = #"4. "
  祢 予 勞 者 以 憩 \fpa 息， 祢 予 疲 者 以 毅 \fpa 力， 祢 予 泣 者 以 撫 \fpa 翼。
  \set stanza = #"6. "
  沒 有 祢 的 聖 寵 \fpa 祐， 人 類 必 無 所 造 \fpa 就， 更 不 免 於 諸 罪 \fpa 咎。
  \set stanza = #"8. "
  求 賜 冥 頑 者 默 \fpa 化， 求 賜 冷 淡 者 光 \fpa 明， 求 賜 迷 途 者 返 \fpa 家。
  \set stanza = #"10. "
  懇 頒 殊 福 於 德 \fpa 勳， 廣 施 救 贖 之 鴻 \fpa 恩， 並 賜 永 生 與 爾 \fpa 民。
}

latinText = \lyricmode {
  \override LyricText.font-name = #"Gentium Book Basic"
  \override LyricText.font-size = #2.25
  
  Ve -- ni San -- cte Spí -- ri -- tus,
  Et e -- mít -- te cǽ -- li -- tus
  Lu -- cis tu -- æ rá -- di -- um.
  
  Ve -- ni pa -- ter páu -- pe -- rum,
  Ve -- ni da -- tor mú -- ne -- rum,
  Ve -- ni lu -- men cór -- di -- um.
  
  Con -- so -- lá -- tor ó -- pti -- me,
  Dul -- cis ho -- spes á -- ni -- mæ,
  Dul -- ce re -- fri -- gé -- ri -- um.

  In la -- bó -- re ré -- qui -- es,
  In æ -- stu tem -- pé -- ri -- es,
  In fle -- tu so -- lá -- ti -- um.

  O lux be -- a -- tís -- si -- ma,
  Re -- ple cor -- dis ín -- ti -- ma
  Tu -- ó -- rum fi -- dé -- li -- um.
  
  Si -- ne tu -- o nú -- mi -- ne,
  Ni -- hil est in hó -- mi -- ne,
  Ni -- hil est in -- nó -- xi -- um.
  
  La -- va quod est sór -- di -- dum,
  Ri -- ga quod est á -- ri -- dum,
  Sa -- na quod est sáu -- ci -- um.
  
  Fle -- cte quod est rí -- gi -- dum,
  Fo -- ve quod est frí -- gi -- dum,
  Re -- ge quod est dé -- vi -- um.
  
  Da tu -- is fi -- dé -- li -- bus,
  In te con -- fi -- dén -- ti -- bus,
  Sa -- crum se -- pte -- ná -- ri -- um.
  
  Da vir -- tú -- tis mé -- ri -- tum,
  Da sa -- lú -- tis éx -- i -- tum,
  Da per -- én -- ne gáu -- di -- um.

  
  % A -- men.  Al -- le -- lu -- ia.
}


latinTextOdd = \lyricmode {
  \override LyricText.font-name = #"Gentium Book Basic"
  \override LyricText.font-size = #2

  \override VerticalAxisGroup.nonstaff-nonstaff-spacing =
  #'((basic-distance . 0)
     (minimum-distance . 3.8) ;; <================ more lower space
     (padding . 0.2)
     (stretchability . 0))

  % 1
  Ve -- ni San -- cte Spí -- ri -- tus,
  Et e -- mít -- te cǽ -- li -- tus
  Lu -- cis tu -- æ rá -- di -- um.
  % 3
  Con -- so -- lá -- tor ó -- pti -- me,
  Dul -- cis ho -- spes á -- ni -- mæ,
  Dul -- ce re -- fri -- gé -- ri -- um.
  % 5
  O lux be -- a -- tís -- si -- ma,
  Re -- ple cor -- dis ín -- ti -- ma
  Tu -- ó -- rum fi -- dé -- li -- um.
  % 7
  La -- va quod est sór -- di -- dum,
  Ri -- ga quod est á -- ri -- dum,
  Sa -- na quod est sáu -- ci -- um.
  % 9
  Da tu -- is fi -- dé -- li -- bus,
  In te con -- fi -- dén -- ti -- bus,
  Sa -- crum se -- pte -- ná -- ri -- um.
  
  % A -- men.  Al -- le -- lu -- ia.
}


latinTextEven = \lyricmode {
  \override LyricText.font-name = #"Gentium Book Basic"
  \override LyricText.font-size = #2.25

  Ve -- ni pa -- ter páu -- pe -- rum,
  Ve -- ni da -- tor mú -- ne -- rum,
  Ve -- ni lu -- men cór -- di -- um.

  In la -- bó -- re ré -- qui -- es,
  In æ -- stu tem -- pé -- ri -- es,
  In fle -- tu so -- lá -- ti -- um.

  Si -- ne tu -- o nú -- mi -- ne,
  Ni -- hil est in hó -- mi -- ne,
  Ni -- hil est in -- nó -- xi -- um.
  
  Fle -- cte quod est rí -- gi -- dum,
  Fo -- ve quod est frí -- gi -- dum,
  Re -- ge quod est dé -- vi -- um.
  
  Da vir -- tú -- tis mé -- ri -- tum,
  Da sa -- lú -- tis éx -- i -- tum,
  Da per -- én -- ne gáu -- di -- um.
  
  % A -- men.  Al -- le -- lu -- ia.
}




\score {
  <<
    \include "懇求主聖神降臨_Veni_Sancte_Spiritus_頌恩626_jianpu.ily"

    \new ChoirStaff <<
      \new Staff = "melody" \with { midiInstrument = "choir aahs" } {
        \melody
      }
      \addlyrics { \chineseTextOdd }
      \addlyrics { \latinTextOdd }
      \addlyrics { \chineseTextEven }
      \addlyrics { \latinTextEven }
    >>
  >>
  \layout {
    indent = #0
    \context {
      \Staff
      \remove "Time_signature_engraver"
    }
    \context {
      \RhythmicStaff
      \remove "Time_signature_engraver"
      \override VerticalAxisGroup.
      default-staff-staff-spacing =
      #'((basic-distance . 0)
         (minimum-distance . 0)
         (padding . 0.5)
         (stretchability . 0))
    }
  }
  \midi {
    \tempo 4=60
  }
}

