% Victimae Paschali Laudes in Chinese and Latin.
%
% Typeset for Mary Help of Christians Chinese Catholic Parish, Edmonton, Canada
% by Anthony Fok, 2015-04-21.
% Revised 2017-03-30;
% Reformatted for slideshow format on 2017-06-01.
%
% This work is licensed under a
% Creative Commons Attribution-ShareAlike 4.0 International License.

%
% Jianpu (numbered musical notation) in
% 懇求主聖神降臨_Veni_Sancte_Spiritus_頌恩626_jianpu.ily
% was generated by Silas C. Brown's excellent jianpu-ly.py script v1.143

% Removed reference to MHOC on 2015-05-07

\version "2.18.2"

\include "../definition.ily"
\include "../mass-slides-mhocp.ily"

\header {
  title = \markup {
    \setbgcolor
    \hspace #4
    \with-color #yellow {
      \kai 請全體起立詠唱：
      \mingheavy 懇求主聖神降臨
      \override #'(font-name . "Gentium Book Basic Bold") {
        %Come, Holy Spirit
        \italic { Veni Sancte Spiritus }
        %VENI SANCTE SPIRITUS
      }
    }
    \hspace #9
  }
  subtitle = \markup {
    \hspace #11
    \with-color #yellow {
      \mingheavy 五旬節(聖神降臨)繼抒詠
      \override #'(font-name . "Gentium Book Basic Bold") {
        Pentecost Sequence: Come, Holy Spirit
      }
    }
  }
  copyright = \markup {
    \override #'(baseline-skip . 2)
    \tiny \with-color #(x11-color 'wheat) {
      \left-column {
        \vspace #1
        \line {
          \concat { \kai 詞： Pope } Innocent III (1198–1216)
          \kai { ※ 譯：採自【聖歌選集 } - No. \concat { 38 { \kai 】 } 1969 } \concat { ( { \kai 香港 } ) }
          \kai { ※ 曲：傳統額我略曲 (第一調式) }
        }
        \line {
          \concat { \kai 來源：新《頌恩》第 626 \kai 首 }
          \concat { ( \kai 天主教香港教區 }
          \concat { 2005 \kai ) }
        }
      }
    }
  }
  tagline = ##f
}

#(set-global-staff-size 28)

\paper {
  %#(set-paper-size "letter")
  %ragged-last = ##t
  
  %left-margin = 0.75\in
  %right-margin = 0.5\in
  % http://www.lilypond.org/doc/v2.18/Documentation/notation/flexible-vertical-spacing-paper-variables
  %markup-system-spacing #'basic-distance = #-20
  %markup-system-spacing #'padding = #2
  %system-system-spacing #'basic-distance = #13.3
  %systems-per-page = 9
  
  #(set-paper-size "1280x720")
  left-margin = 0.5\in
  right-margin = 0.5\in
  top-margin = 0.1\in
  bottom-margin = 0.1\in

  top-system-spacing.padding = #0
  markup-system-spacing.padding = #3
  system-system-spacing.padding = #0.5
  
  %ragged-last-bottom = ##f
  %ragged-right = ##t
  ragged-bottom = ##t

  oddHeaderMarkup = \markup {
    \setbgcolor
    \with-color #white
    
    \fill-line {
      %{
      \on-the-fly \print-page-number-check-first
      {
        "" %〈懇求主聖神降臨〉
        \fromproperty #'page:page-number-string
      }
      %}
    }
  }
  evenHeaderMarkup = \oddHeaderMarkup

}


global = {
  \key c \major
  %\time 4/4
  \cadenzaOn
  % http://comments.gmane.org/gmane.comp.gnu.lilypond.general/86734
}

bb = { | \bar "'" }
bl = { | \bar "|" }
bll = { | \bar "||" }

sd = { \set melismaBusyProperties = #'() \slurDashed }
ss = { \slurSolid \unset melismaBusyProperties }

nn = \once \override Voice.Accidental.stencil = ##f

melody = \relative c' {
  \tempo "Recitativo legato"
  \global
  \autoBeamOff
  
  %\unfoldRepeats
  %d8 e fis g fis[ e] d e4 \bl  g8 a b c b[ a g] a b4 \bl d,8 e g a g[ fis e] d e4 \bll
  
  %\repeat volta 2 {
    c8 d e f e d c d4 \bl
    f8 g a bes! a[ g f] g a4 \bl
    c,8 d f g f[ e d] c d4 \bll \break
  %}
  
  %\break
  %\vspace #11
  
  c8 d e f e d c d4 \bl
    f8 g a bes! a g[ f] g a4 \bl
    c,8 d f g f e[ d] c d4 \bll \break
  
  \pageBreak
  %{b'8 d e e d[
  \once \override Voice.Accidental.stencil = ##f
  cis] d e4 \bl  d8 b d[ cis] a g[ fis] e d4 \bl  a'8 g a[ b] a g[ fis e] d e4 \bll
  %}
  \unfoldRepeats
  
    a'8 c d d c \nn b c d4 \bl
    c8 a c b g f e d c4 \bl
    g'8 f g a g f[ e] d c d4 \bll
  
  a'8 c d d c \nn b c d4 \bl
    c8 a c b[ g] f e d c4 \bl
    g'8 f g a g f[ e d] c d4 \bll
  
  \pageBreak
  %e'8 e d[ cis] d e[ d] cis b4 \bl  g8 e d e g a g4 \bl  a8[ b] c b a g[ fis e] d e4 \bll
  \unfoldRepeats
  \repeat volta 2 {
    d'8 d c[ \nn b] c d[ c] b a4 \bl
    f8 d c d f[ g] f4 \bl
    g8[ a] bes a g f[ e d] c d4 \bll
  }
  
  %{b'8 d
  \once \override Voice.Accidental.stencil = ##f
  cis[ b] cis d[ cis] b a4 \bl  b8 b g[ fis] g a[ g] fis e4 \bl  fis8 a b a d cis b4 \bll
  %}
  \unfoldRepeats
  \repeat volta 2 {
    a'8 c \nn b[ a] b c[ b] a g4 \bl  a8 a f[ e] f g[ f] e d4 \bl  e8 g a g c b a4 \bll
  }
  
  %e8 e a, b d cis b4 \bl  b8 c b[ a] b g a g4 \bl  fis8 a b e, g fis e4 \bll
  \pageBreak
  \unfoldRepeats
  \repeat volta 2 {
    d8 d g, a c \nn b a4 \bl  a8 bes a[ g] a f g f4 \bl  e8 g a d, f e d4 \bll
  }
  
  \pageTurn
  d8[ e d] c4( d) \bb  c8 f e[ d] d4 | \bar "|."
}

fpa = \once \override LyricText #'self-alignment-X = #-0.72
fpb = \once \override LyricText #'self-alignment-X = #0.72

cantoneseText = \lyricmode {
  %\override LyricText.font-size = #2.5
  
  \set stanza = #"1. "
  懇 求 主 聖 神 降 \fpa 臨， 賜 我 等 天 上 神 \fpa 光， 啟 導 諸 信 者 之 \fpa 心。
  \set stanza = #"2. "
  祢 是 窮 人 的 慈 \fpa 父， 祢 是 恩 寵 的 施 \fpa 主， 祢 是 眾 心 的 暉 \fpa 曙。

  \set stanza = #"3. "
  祢 是 苦 者 的 安 \fpa 慰， 祢 是 善 靈 的 良 \fpa 衛， 祢 普 施 珍 美 德 \fpa 惠。
  \set stanza = #"4. "
  祢 予 勞 者 以 憩 \fpa 息， 祢 予 疲 者 以 毅 \fpa 力， 祢 予 泣 者 以 撫 \fpa 翼。

 
}

chineseTextOdd = \lyricmode {
  \override LyricText.font-size = #2.5

  \set stanza = #"1. "
  懇 求 主 聖 神 降 \fpa 臨， 賜 我 等 天 上 神 \fpa 光， 啟 導 諸 信 者 之 \fpa 心。
  \set stanza = #"3. "
  祢 是 苦 者 的 安 \fpa 慰， 祢 是 善 靈 的 良 \fpa 衛， 祢 普 施 珍 美 德 \fpa 惠。
  \set stanza = #"5. "
  祢 是 普 世 的 福 \fpa 星， 祢 以 神 妙 的 光 \fpa 明， 照 耀 信 眾 的 心 \fpa 靈。
  \set stanza = #"7. "
  請 清 除 一 切 穢 \fpa 污， 請 灌 澤 心 靈 涸 \fpa 沽， 請 療 我 們 的 殘 \fpa 腐。
  \set stanza = #"9. "
  諸 欽 崇 祢 的 靈 \fpa 魂， 特 虔 誠 向 祢 奔 \fpa 馳， 祈 充 以 聖 神 七 \fpa 恩。

  \set stanza = #"(齊唱)"
  A -- men.  Al -- le -- lú -- ia.
}

mandarinText = \lyricmode {
  %\override LyricText.font-size = #2.5
  
  \set stanza = #"1. "
  天 主 圣 神 求 祢 降 临， 从 至 高 的 天 _ \fpa 庭， 放 射 出 祢 的 光 明。
  \set stanza = #"2. "
  穷 人 慈 父 求 速 降 \fpa 临！ 恩 宠 施 主 求 祢 降 \fpa 临，
  心 灵 真 光 求 祢 降 \fpa 临。

  \set stanza = #"3. "
  最 慰 人 心 灵 _ 圣 \fpa 神， 
  我 们 衷 心 欢 迎 的 佳 \fpa 宾！
  人 生 旅 途 舒 适 的 荫 \fpa 庇。
  \set stanza = #"4. "
  在 劳 苦 中 祢 是 憩 \fpa 息， 在 酷 热 里 祢 是 清 \fpa 风；
  在 悲 痛 是 祢 是 慰 \fpa 藉。

 \set stanza = #"5. "
  祢 是 幸 福 的 真 \fpa 光， 求 祢 照 耀 我 \fpa 们， 充 满 祢 信 者 的 身 \fpa 心。
  \set stanza = #"6. "
  除 非 有 祢 的 助 \fpa 佑， 人 便 一 无 所 \fpa 有， 人 更 是 一 无 是 \fpa 处。

  \set stanza = #"7. "
  求 祢 洗 净 我 们 的 污 \fpa 秽， 求 祢 医 治 我 们 的 创 \fpa 伤， 滋 润 我 们 的 憔 \fpa 悴。
  \set stanza = #"8. "
  求 祢 驯 服 顽 强 的 \fpa 人， 求 祢 温 暖 冷 酷 的 \fpa 心，引 迷 途 人脱 迷 \fpa 津。

  \set stanza = #"9. "
  信 祢 的 人 求 扶 \fpa 助， 赐 予 丰 富 的 宠 \fpa 恩， 施 以 慈 爱 的 照 \fpa 顾。
  \set stanza = #"10. "
  求 赐 修 德 的 能 \fpa 力， 求 赐 善 终 的 洪 \fpa 恩， 施 我 永 福的 欢 \fpa 欣。

  \set stanza = #"(齊唱)"
  \override LyricText.font-name = #"Gentium Book Basic"
  \override LyricHyphen.height = #0.95
  阿 \fpa 们。 阿 来 路 \fpa 亚。
}

chineseTextEven = \lyricmode {
  \override LyricText.font-size = #2.5

  \set stanza = #"2. "
  祢 是 窮 人 的 慈 \fpa 父， 祢 是 恩 寵 的 施 \fpa 主， 祢 是 眾 心 的 暉 \fpa 曙。
  \set stanza = #"4. "
  祢 予 勞 者 以 憩 \fpa 息， 祢 予 疲 者 以 毅 \fpa 力， 祢 予 泣 者 以 撫 \fpa 翼。
  \set stanza = #"6. "
  沒 有 祢 的 聖 寵 \fpa 祐， 人 類 必 無 所 造 \fpa 就， 更 不 免 於 諸 罪 \fpa 咎。
  \set stanza = #"8. "
  求 賜 冥 頑 者 默 \fpa 化， 求 賜 冷 淡 者 光 \fpa 明， 求 賜 迷 途 者 返 \fpa 家。
  \set stanza = #"10. "
  懇 頒 殊 福 於 德 \fpa 勳， 廣 施 救 贖 之 鴻 \fpa 恩， 並 賜 永 生 與 爾 \fpa 民。
}

latinText = \lyricmode {
  \override LyricText.font-name = #"Gentium Book Basic"
  \override LyricText.font-size = #0.5
  \override LyricHyphen.height = #0.55
  
  Ve -- ni San -- cte Spí -- ri -- tus,
  Et e -- mít -- te cǽ -- li -- tus
  Lu -- cis tu -- æ rá -- di -- um.
  
  Ve -- ni pa -- ter páu -- pe -- rum,
  Ve -- ni da -- tor mú -- ne -- rum,
  Ve -- ni lu -- men cór -- di -- um.
  
  Con -- so -- lá -- tor ó -- pti -- me,
  Dul -- cis ho -- spes á -- ni -- mæ,
  Dul -- ce re -- fri -- gé -- ri -- um.

  In la -- bó -- re ré -- qui -- es,
  In æ -- stu tem -- pé -- ri -- es,
  In fle -- tu so -- lá -- ti -- um.

  O lux be -- a -- tís -- si -- ma,
  Re -- ple cor -- dis ín -- ti -- ma
  Tu -- ó -- rum fi -- dé -- li -- um.
  
  Si -- ne tu -- o nú -- mi -- ne,
  Ni -- hil est in hó -- mi -- ne,
  Ni -- hil est in -- nó -- xi -- um.
  
  La -- va quod est sór -- di -- dum,
  Ri -- ga quod est á -- ri -- dum,
  Sa -- na quod est sáu -- ci -- um.
  
  Fle -- cte quod est rí -- gi -- dum,
  Fo -- ve quod est frí -- gi -- dum,
  Re -- ge quod est dé -- vi -- um.
  
  Da tu -- is fi -- dé -- li -- bus,
  In te con -- fi -- dén -- ti -- bus,
  Sa -- crum se -- pte -- ná -- ri -- um.
  
  Da vir -- tú -- tis mé -- ri -- tum,
  Da sa -- lú -- tis éx -- i -- tum,
  Da per -- én -- ne gáu -- di -- um.

  
  % A -- men.  Al -- le -- lu -- ia.
}


latinTextOdd = \lyricmode {
  \override LyricText.font-name = #"Gentium Book Basic"
  \override LyricText.font-size = #2

  \override VerticalAxisGroup.nonstaff-nonstaff-spacing =
  #'((basic-distance . 0)
     (minimum-distance . 3.8) ;; <================ more lower space
     (padding . 0.2)
     (stretchability . 0))

  % 1
  Ve -- ni San -- cte Spí -- ri -- tus,
  Et e -- mít -- te cǽ -- li -- tus
  Lu -- cis tu -- æ rá -- di -- um.
  % 3
  Con -- so -- lá -- tor ó -- pti -- me,
  Dul -- cis ho -- spes á -- ni -- mæ,
  Dul -- ce re -- fri -- gé -- ri -- um.
  % 5
  O lux be -- a -- tís -- si -- ma,
  Re -- ple cor -- dis ín -- ti -- ma
  Tu -- ó -- rum fi -- dé -- li -- um.
  % 7
  La -- va quod est sór -- di -- dum,
  Ri -- ga quod est á -- ri -- dum,
  Sa -- na quod est sáu -- ci -- um.
  % 9
  Da tu -- is fi -- dé -- li -- bus,
  In te con -- fi -- dén -- ti -- bus,
  Sa -- crum se -- pte -- ná -- ri -- um.
  
  % A -- men.  Al -- le -- lu -- ia.
}


latinTextEven = \lyricmode {
  \override LyricText.font-name = #"Gentium Book Basic"
  \override LyricText.font-size = #2.25

  Ve -- ni pa -- ter páu -- pe -- rum,
  Ve -- ni da -- tor mú -- ne -- rum,
  Ve -- ni lu -- men cór -- di -- um.

  In la -- bó -- re ré -- qui -- es,
  In æ -- stu tem -- pé -- ri -- es,
  In fle -- tu so -- lá -- ti -- um.

  Si -- ne tu -- o nú -- mi -- ne,
  Ni -- hil est in hó -- mi -- ne,
  Ni -- hil est in -- nó -- xi -- um.
  
  Fle -- cte quod est rí -- gi -- dum,
  Fo -- ve quod est frí -- gi -- dum,
  Re -- ge quod est dé -- vi -- um.
  
  Da vir -- tú -- tis mé -- ri -- tum,
  Da sa -- lú -- tis éx -- i -- tum,
  Da per -- én -- ne gáu -- di -- um.
  
  % A -- men.  Al -- le -- lu -- ia.
}




\score {
  <<
    \include "懇求主聖神降臨_Veni_Sancte_Spiritus_頌恩626_幻燈.jianpu.ily"

    \new ChoirStaff <<
      \new Staff = "melody" \with { midiInstrument = "choir aahs" } {
        \melody
      }
      %\addlyrics { \cantoneseText }
      \addlyrics { \mandarinText }
      %\addlyrics { \englishText }
      \addlyrics { \latinText }
    >>
  >>
  \layout {
    indent = #0
    \context {
      \Score
      \applyContext #(override-color-for-all-grobs (x11-color 'wheat))
      % Colour the whole score, not just the staff;
      % See http://lilypond.1069038.n5.nabble.com/Coloring-volta-bracket-td189493.html
    }
    \context {
      \Staff
      \remove "Time_signature_engraver"
      
      % Reduce staff size for slides
      fontSize = #-3
      \override StaffSymbol.staff-space = #(magstep -3)
      \override StaffSymbol.thickness = #(magstep -3)
    }
    \context {
      \RhythmicStaff
      \remove "Time_signature_engraver"
      \override VerticalAxisGroup.
      default-staff-staff-spacing =
      #'((basic-distance . 2)
         (minimum-distance . 0)
         (padding . 0)
         (stretchability . 0))
    }
    \context {
      \Lyrics
      \override LyricText.font-name = #"DFKai-SB"
      %\override LyricText.font-name = #"DFHKStdKai-B5"
      %\override LyricText.font-name = #"HanWangYanKai"
      %\override LyricText.font-name = #"cwTeXKai"
      \override LyricText.font-size = #5
      \override LyricText.color = #white
      %\override LyricExtender.color = #white
      \override StanzaNumber.color = #yellow

      \override VerticalAxisGroup #'staff-affinity = #CENTER
    }
  }
  \midi {
    \tempo 4=60
  }
}
